module.exports = {
  someSidebar: {
    'Introduction': ['overview'],
    'Documentations': [
      'documentation-overview',
      'developer-onboarding',
      'guidelines',
      'project-onboarding',
      'code-of-conduct',
      'code-of-ethics',
      'review-reference',
      'codenames',
      'branding',
      'deployment',
      'devops',
      'security',
      'testing',
      'contributors-guide',
      'branch',
      'commits',
      'issue-vs-pull-request',
    ],
    'Project: Company API': ['project-api'],
    'Project: Database Seeder': ['project-seeder'],
    'Project: XConnect': ['project-xconnect'],
    'Project: XtendOps Careers': ['project-careers'],
    'Project: iFix': ['project-ifix'],
    'Project: Slack Messenger': ['project-slack'],
    'Project: Status Checker': ['project-status'],
    'Project: Monitoring': ['project-monitoring'],
    'Style Guide': ['documentation-style-markdown', 'documentation-style-mdx'],
  },
};
